kind: pipeline
name: exort_se418

steps:
- name: build
  image: maven:latest
  commands:
  - mvn clean package
  - mv ./target/se418-0.1.jar ~/
  when:
    event:
    - push

- name: deploy
  image: plugins/docker
  settings:
      repo: se418
      tags: v1
      dry_run: true
