kind: pipeline
name: exort_se418

steps:
- name: build
  image: maven:latest
  commands:
  - mvn clean package
  when:
    event:
    - push

- name: deploy
  image: plugins/docker
  settings:
      repo: se418
      tags: v1
      dry_run: true
      
- name: run
  image: plugins/docker
  script:
      - /bin/bash ./deploy.sh
