kind: pipeline
name: drone_test

steps:
- name: build
  image: maven:latest
  commands:
  - mvn clean package
  volumes:
  - name: ci-test
    path: /ci
  when:
    event:
    - pull-request
    - push
    branch:
    - master
