kind: pipeline
name: exort_se418

steps:
#- name: restore-cache
#  image: drillster/drone-volume-cache
#  volumes:
#  - name: cache
#    path: /cache
#  settings:
#    restore: true
#    mount:
#      - /home/ubuntu/.m2

- name: build
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  commands:
  - cd ./se418ribbon
  - mvn clean package
  - cd ../se418gateway
  - mvn clean package
  - cd ../eureka
  - mvn clean package
  - cd ../ladder
  - mvn clean package

#- name: rebuild-cache
#  image: drillster/drone-volume-cache
#  volumes:
#  - name: cache
#    path: /cache
#  settings:
#    rebuild: true
#    mount:
#      - /home/ubuntu/.m2

- name: scp
  image: appleboy/drone-scp
  settings:
    host: 212.64.27.71 
    username: ubuntu
    password: 
        from_secret: server_ci
    target: /home/ubuntu/deploy/${DRONE_REPO}/
    source:
    - eureka/target/eureka-0.0.1-SNAPSHOT.jar
    - eureka/Dockerfile
    - ladder/target/se418-0.1.jar
    - ladder/Dockerfile
    - ribbon/target/se418ribbon-0.0.1-SNAPSHOT.jar 
    - ribbon/Dockerfile
    - gateway/target/se418gateway-0.0.1-SNAPSHOT.jar 
    - gateway/Dockerfile
    - docker-compose.yml
    rm: true

- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: 212.64.27.71 
    username: ubuntu
    password: 
        from_secret: server_ci
    script:
      - docker rm -f se418
      - docker rm -f gateway
      - docker rm -f ribbon
      - docker rm -f eureka
      #- docker network rm springcloud
      #- docker network create springcloud
      - cd /home/ubuntu/deploy/${DRONE_REPO}/eureka
      - docker build -t exort/eureka .
      #- docker run -d --name eureka -p 1111:1111 exort/eureka
      - cd /home/ubuntu/deploy/${DRONE_REPO}/ribbon
      - docker build -t exort/ribbon .
      #- docker run -d --name ribbon --link eureka:eureka -p 8000:8000 exort/ribbon
      - cd /home/ubuntu/deploy/${DRONE_REPO}/gateway
      - docker build -t exort/gateway .
      #- docker run -d --name gateway --link eureka:eureka -p 7000:7000 exort/gateway
      - cd /home/ubuntu/deploy/${DRONE_REPO}/ladder
      - docker build -t exort/se418 .
      #- docker run -d --name se418 -p 8050:8050 exort/se418
      - docker-compose up -d

volumes:
  - name: cache
    host:
      path: /tmp/cache
