kind: pipeline
name: exort_se418

steps:
- name: build
  image: maven:latest
  commands:
  - mvn clean package
  when:
    event:
    - push

- name: deploy
  image: plugins/docker
  commands:
  - docker build -t se418:v1 .
  - docker run --name=se418 -d -p 9090:8080 se418:v1
