kind: pipeline
name: exort_se418

steps:
- name: build
  image: thomasf/drone-mvn
  volumes:
  - name: cache
    path: /root/.m2
  #- name: mvn_build
  #  path: /drone/src
  commands:
  - cd ./feign
  - mvn clean package
  - cd ../se418gateway
  - mvn clean package
  - cd ../eureka
  - mvn clean package
  - cd ../ladder
  - mvn clean package
  - cd ..
  - pwd

#- name: scp
#  image: appleboy/drone-scp
#  settings:
#    host: 212.64.27.71 
#    username: ubuntu
#    password: 
#        from_secret: server_ci
#    target: /home/ubuntu/deploy/${DRONE_REPO}/
#    source:
#    - eureka/target/eureka-0.0.1-SNAPSHOT.jar
#    - eureka/Dockerfile
#    - feign/target/se418-0.1.jar
#    - feign/Dockerfile
#    - ladder/target/ladder-0.0.1-SNAPSHOT.jar 
#    - ladder/Dockerfile
#    - se418gateway/target/se418gateway-0.0.1-SNAPSHOT.jar 
#    - se418gateway/Dockerfile
#    - docker-compose.yml
#    rm: true

- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: 212.64.27.71 
    username: ubuntu
    password: 
        from_secret: server_ci
    script:
      - docker stack rm eurekacluster
      #- docker rm -f se418
      #- docker rm -f gateway
      #- docker rm -f ribbon
      #- docker rm -f eureka
      #- docker network rm springcloud
      #- docker network create springcloud
      #- pwd
      - cd /home/ubuntu/deploy/${DRONE_REPO}/eureka
      - docker build -t exort/eureka .
      #- docker run -d --name eureka -p 1111:1111 exort/eureka
      - cd /home/ubuntu/deploy/${DRONE_REPO}/feign
      - docker build -t exort/feign .
      #- docker run -d --name ribbon --link eureka:eureka -p 8000:8000 exort/ribbon
      - cd /home/ubuntu/deploy/${DRONE_REPO}/se418gateway
      - docker build -t exort/gateway .
      #- docker run -d --name gateway --link eureka:eureka -p 7000:7000 exort/gateway
      - cd /home/ubuntu/deploy/${DRONE_REPO}/ladder
      - docker build -t exort/ladder .
      #- docker run -d --name se418 -p 8050:8050 exort/se418
      - cd /home/ubuntu/deploy/${DRONE_REPO}
      #- docker-compose up -d
      #- docker swarm leave
      #- docker swarm init
      - docker network create --driver overlay eurekacluster_springcloud
      - docker stack deploy -c docker-compose.yml eurekacluster

volumes:
  - name: cache
    host:
      path: /home/ubuntu/repo
  - name: mvn_build
    host:
      path: /home/ubuntu/deploy/exorteam/SE418
