kind: pipeline
name: exort_se418

steps:
- name: build
  image: maven:latest
  commands:
  - mvn clean package
  when:
    event:
    - push

- name: scp
  image: appleboy/drone-scp
  settings:
    host: 212.64.27.71 
    username: ubuntu
    password: 
        from_secret: server_ci
    target: /root/deploy/${DRONE_REPO}
    source:
    - build
    - Dockerfile
    rm: true
  #when:
  #  branch:
  #  - master

- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: 212.64.27.71 
    username: ubuntu
    password: 
        from_secret: server_ci
    script:
      - cd /root/deploy/${DRONE_REPO}
      - docker build -t exort/se418 .
      - docker rm -f se418
      - docker run -d --name se418 -p 8080:8080 exort/se418
  #when:
  #  branch:
  #  - master
