version: "3"
services:
    eureka:
        image: exort/eureka
        #container_name: eureka
        hostname: eureka
        #restart: always
        ports:
            - 1111:1111
        networks:
            - springcloud

    feign:
        image: exort/feign
        #container_name: ribbon
        #restart: always
        environment:
            - spring.profiles.active=feign
        ports:
            - 8050:8050
        #links:
        #    - eureka
        networks:
            - springcloud

    gateway:
        image: exort/gateway
        #container_name: gateway
        #restart: always
        environment:
            - spring.profiles.active=gateway
        ports:
            - 7000:7000
        #links:
        #    - eureka
        #    - ribbon
        networks:
            - springcloud

    ladder:
        image: exort/ladder
        #container_name: ladder
        #restart: always
        #ports:
        #    - 8010:8010
        environment:
            - spring.profiles.active=ladder
        #links:
        #    - eureka
        #    - ribbon
        #    - gateway
        networks:
            - springcloud

    ladder2:
        image: exort/ladder
        environment:
            - spring.profiles.active=ladder
        networks:
            - springcloud

networks:
    springcloud:
        driver: overlay
