version: "2"
services:
    eureka:
        image: exort/eureka
        hostname: eureka
        restart: always
        ports:
            - 1111:1111

    ribbon:
        image: exort/ribbon
        restart: always
        ports:
            - 8000:8000
        links:
            - "eureka"

    gateway:
        image: exort/gateway
        restart: always
        ports:
            - 7000:7000
        links:
            - "eureka"
            - "ribbon"

    ladder:
        image: exort/se418
        restart: always
        ports:
            - 8050:8050
        links:
            - "eureka"
            - "ribbon"
            - "gateway"

